import { mkdir,writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const modulePath=process.argv[2];
const { chromium }=modulePath?await import(pathToFileURL(modulePath)):await import('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const base=process.env.QA_URL||'http://127.0.0.1:4173/ai-evolution-lab/';
const report=[];
try{
  await page.goto(base);
  await page.waitForTimeout(250);
  assert.equal(await page.locator('.milestone').count(),18,'18 history nodes render');
  assert.equal(await page.locator('.lab-header').count(),6,'all six laboratories mount');
  await page.locator('#perceptron .train-epoch').click();
  assert.match(await page.locator('#perceptron .lab-status').innerText(),/轮次 1/);
  await page.locator('#perceptron .dataset-select').selectOption('xor');
  assert.match(await page.locator('#perceptron .lab-status').innerText(),/轮次 0/);
  await page.locator('#eliza input').fill('我觉得 <script>测试</script>');
  await page.locator('#eliza .chat-form button').click();
  assert.match(await page.locator('#eliza .chat-log').innerText(),/<script>测试<\/script>/);
  await page.locator('#eliza .rule-toggle').click();
  assert.equal(await page.locator('#eliza .rule-panel').isVisible(),true);
  const before=await page.locator('#alexnet .output-canvas').evaluate(c=>c.toDataURL());
  await page.locator('#alexnet .filter-select').selectOption('horizontal');
  assert.notEqual(await page.locator('#alexnet .output-canvas').evaluate(c=>c.toDataURL()),before);
  await page.locator('#alphago .train-episodes').click();
  await page.waitForFunction(()=>document.querySelector('#alphago .lab-status').textContent.includes('回合 100'));
  const old=await page.locator('#transformer .attention-formula').innerText();
  await page.locator('#transformer .attention-sentence button').nth(3).click();
  assert.notEqual(await page.locator('#transformer .attention-formula').innerText(),old);
  const noise=await page.locator('#diffusion canvas.main-diffusion').evaluate(c=>c.toDataURL());
  await page.locator('#diffusion .step-range').fill('40');
  assert.notEqual(await page.locator('#diffusion canvas.main-diffusion').evaluate(c=>c.toDataURL()),noise);
  await page.locator('#perceptron .quiz summary').click();
  await page.locator('#perceptron .quiz-options button').nth(1).click();
  assert.match(await page.locator('#perceptron .quiz-feedback').innerText(),/理解正确/);
  await page.goto(base+'#transformer');
  await page.waitForFunction(()=>{const y=document.querySelector('#transformer').getBoundingClientRect().top;return y>=0&&y<190});
  await page.locator('#transformer .attention-sentence button').nth(0).click();
  await page.locator('#era-navigation a[data-era="rules"]').click();
  await page.waitForFunction(()=>location.hash==='#eliza');
  await page.goBack();
  await page.waitForFunction(()=>location.hash==='#transformer');
  await page.locator('#alphago .watch-policy').click();
  await page.locator('#alphago .reset').click();
  await page.waitForTimeout(350);
  assert.equal(await page.locator('#alphago .lab-status').innerText(),'回合 0\n到达目标 0 次');
  await page.locator('#diffusion .play-diffusion').click();
  await page.locator('#diffusion .reset').click();
  await page.waitForTimeout(200);
  assert.equal(await page.locator('#diffusion .step-range').inputValue(),'0');
  report.push('desktop: 18 nodes, 6 labs, all lab controls, quiz feedback, direct hash');
  const out=process.env.QA_OUTPUT||'../../work/qa';await mkdir(out,{recursive:true});
  await page.goto(base);await page.screenshot({path:out+'/desktop.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile no overflow');
  assert.ok(await page.locator('.diffusion-dataset').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'all dataset examples fit mobile panel');
  await page.screenshot({path:out+'/mobile.png',fullPage:false});
  await page.goto(base+'#diffusion');await page.waitForTimeout(100);
  await page.screenshot({path:out+'/diffusion.png',fullPage:false});
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
  assert.deepEqual(errors,[],'no browser exceptions');
  report.push('mobile: no horizontal overflow; reduced-motion behavior; zero browser exceptions');
  await writeFile(out+'/report.json',JSON.stringify({passed:true,checks:report},null,2));
  console.log(JSON.stringify({passed:true,checks:report}));
}finally{await browser.close();}
