import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const {chromium}=await import(pathToFileURL(process.argv[2]));
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const base=process.env.QA_URL||'http://127.0.0.1:4173/ai-evolution-lab/';
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
  // Simulate the old module left in a browser cache after footer removal.
  await page.route(/\/scripts\/stages\.js$/,route=>route.fulfill({contentType:'text/javascript',body:"export function mountStages(){document.querySelector('.closing').append(null)}"}));
  await page.goto(base);
  assert.equal(await page.title(),'AI Evolution Lab');
  assert.equal(await page.locator('.site-header .brand,.site-header .github-link').count(),0,'header edge branding removed');
  assert.equal(await page.locator('#next-stage').count(),1,'stage navigation exists');
  await page.locator('#next-stage').click();
  assert.ok(await page.evaluate(()=>document.querySelector('main').getAnimations({subtree:true}).length>=3),'layered transition active');
  assert.equal(await page.locator('.milestone:visible').count(),1);
  assert.equal(await page.locator('#neuron').isVisible(),true);
  await page.locator('#next-stage').click();
  assert.equal(await page.locator('#turing').isVisible(),true);
  await page.locator('#previous-stage').click();
  assert.equal(await page.locator('#neuron').isVisible(),true);
  await page.goBack();
  await page.waitForFunction(()=>document.querySelector('#turing').checkVisibility());
  await page.goto(base+'#transformer');
  await page.waitForFunction(()=>document.querySelector('#transformer').checkVisibility());
  assert.equal(await page.locator('.milestone:visible').count(),1);
  await page.locator('#next-stage').click();
  assert.equal(await page.locator('#bert').isVisible(),true);
  await page.locator('#previous-stage').click();
  await page.locator('#previous-stage').click();
  await page.locator('#previous-stage').click();
  assert.equal(await page.locator('#gan').isVisible(),true,'rapid navigation reaches the intended stage');
  await page.goto(base+'#diffusion');
  await page.locator('#diffusion .play-diffusion').click();
  await page.waitForTimeout(130);
  await page.locator('#next-stage').click();
  const paused=await page.locator('#diffusion .step-range').inputValue();
  await page.waitForTimeout(250);
  assert.equal(await page.locator('#diffusion .step-range').inputValue(),paused,'hidden experiment stops playback');
  await page.setViewportSize({width:390,height:844});
  await page.goto(base+'#perceptron');
  const rect=await page.locator('#next-stage').boundingBox();
  assert.ok(rect.y>=0&&rect.y+rect.height<=844,'next button always visible on mobile');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),'no long scrolling page');
  await page.locator('#next-stage').click();assert.equal(await page.locator('#eliza').isVisible(),true);
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('#next-stage').click();
  assert.equal(await page.locator('#expert').isVisible(),true);
  assert.equal(await page.evaluate(()=>document.querySelector('main').getAnimations({subtree:true}).length),0,'reduced motion skips transitions');
  await page.goto(base+'#about');
  assert.ok(!(await page.locator('.closing').innerText()).includes('null'),'cached module cannot insert null');
  assert.equal(await page.locator('footer').count(),0);
  assert.deepEqual(errors,[]);
  const out=process.env.QA_OUTPUT||'../../work/stage-qa';await mkdir(out,{recursive:true});
  await page.screenshot({path:out+'/mobile.png'});
  await page.setViewportSize({width:1440,height:1000});await page.goto(base+'#transformer');await page.waitForTimeout(400);await page.screenshot({path:out+'/desktop.png'});
  console.log('PASS: single-stage screens, next/previous/back, rapid navigation, direct links, hidden playback pause, mobile fixed controls, reduced motion, header removals.');
}finally{await browser.close()}
